---
abstract: 'User management and authorization for web applications and subscription-based services.'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Entities
requires:
  Abilities: 0
  Abilities::Features: 0
  Carp: 0
  DateTime: 0
  DateTime::Format::ISO8601: 0
  Digest::MD5: 0
  MongoDB: 0
  Moo: 0
  Moo::Role: 0
  MooX::Types::MooseLike::Base: 0
  MooX::Types::MooseLike::Email: 0
  Scalar::Util: 0
  namespace::autoclean: 0
  perl: 5.006
  strict: 0
resources:
  homepage: https://github.com/ido50/Entities
  repository: https://github.com/ido50/Entities.git
version: 0.4
